services:
  app:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDatabase:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=saturdaySpring
    ports:
      - "8082:8082"
    depends_on:
      - postgresDatabase
    restart: unless-stopped

  postgresDatabase:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2005
      POSTGRES_DB: sabak
      PGDATA: /data/sabak
    #    volumes:
    #      - db\
    #      - :/data/postgres
    ports:
      - "5432:5432"
    restart: always

#volumes:
#  db: /data/